//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MediaServer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MEDIASERVER_DIALOG          102
#define IDD_MODIFYUI                    103
#define IDR_MAINFRAME                   128
#define IDD_TEMP_DLG                    131
#define IDD_LOADOBJ_DLG                 133
#define IDC_HAND_CLOSE                  135
#define IDC_HAND_OPEN                   136
#define IDD_ADD_FOLDER_DLG              137
#define IDD_EDIT_TAG_DLG                139
#define IDD_DIALOG1                     140
#define IDD_SEARCH_TAG_DLG              141
#define IDD_TIMELINE_SETTINGS_DLG       142
#define IDD_EDIT_CMD_DLG                143
#define IDD_EDIT_EFFECT_INDEX_DLG       144
#define IDD_SERVER_LIST_DLG             146
#define IDD_DIALOG2                     148
#define IDD_WAITING_DLG                 148
#define IDD_SETGRID_DLG                 150
#define IDD_ADD_RTSP_URL_DLG            152
#define IDD_AREA_OPTION_DLG             154
#define IDD_MOVE_TO_DLG                 155
#define IDD_EDGEBLEND_DLG               156
#define IDD_PAN_BLD_DLG                 158
#define IDD_AUDIO_CONFIG_DLG            159
#define IDD_SETTINGS_DLG                160
#define IDC_OPEN_VIDEO_PATH             1000
#define IDC_FOLDER_NAME                 1001
#define IDC_VIDEO_PATH_EDIT             1002
#define IDC_EDIT2                       1003
#define IDC_TAG                         1004
#define IDC_BUTTON2                     1005
#define IDC_OPEN_OBJ_PATH               1006
#define IDC_KEYWORD                     1007
#define IDC_FULLSCR_CHK                 1008
#define IDC_PANNEL_LIST                 1009
#define IDC_EFFECT_LIST                 1010
#define IDC_XNUM_COMBO                  1011
#define IDC_YNUM_COMBO                  1012
#define IDC_STATICX                     1013
#define IDC_STATICY                     1014
#define IDC_STATICWHR                   1015
#define IDC_WHRATIO_COMBO               1016
#define IDC_IMG_EFFECT_LIST             1017
#define IDC_IMG_STATIC                  1018
#define IDC_SHOW_GROUND_CHK             1019
#define IDC_SHOW_AXIS_CHK               1020
#define IDC_SLIDER1                     1021
#define IDC_SLIDER2                     1022
#define IDC_SLIDER3                     1023
#define IDC_SLIDER4                     1024
#define IDC_SLIDER5                     1025
#define IDC_SLIDER6                     1026
#define IDC_SHOW_Model_LINE_CHK         1027
#define IDC_MOVE_MDL_CHK                1028
#define IDC_ROTATE_MDL_CHK              1029
#define IDC_RUN_Model_LINE_CHK          1030
#define IDC_LEVEL_STC                   1031
#define IDC_PARM1_STC                   1032
#define IDC_PARM2_STC                   1033
#define IDC_PARM3_STC                   1034
#define IDC_PARM4_STC                   1035
#define IDC_PARM5_STC                   1036
#define IDC_ONLY_VIDEO_CHK              1037
#define IDC_VIEWPORT_COMBO              1038
#define IDC_HAVE_END_SUF_CHK            1039
#define IDC_VIDEO_PATH_COMB0            1040
#define IDC_OBJ_PATH_EDIT               1041
#define IDC_ZOOM_COMBO                  1042
#define IDC_ZOOM_SLIDER                 1043
#define IDC_OBJ_FAPTH_STATIC            1044
#define IDC_TIMELINE_NAME               1045
#define IDC_TIMELINE_ID                 1046
#define IDC_CMD_NAME                    1047
#define IDC_CMD_LIST                    1048
#define IDC_EVENT_LIST                  1049
#define IDC_OPEN_VIDEO_PATH2            1050
#define IDC_EFFECT_INDEX                1051
#define IDC_MASTER                      1052
#define IDC_IP_ADDRESS                  1053
#define IDC_PORT                        1054
#define IDC_START                       1055
#define IDC_STOP                        1056
#define IDC_SEARCH                      1057
#define IDC_SERVER_LIST                 1058
#define IDC_PROGRESS1                   1059
#define IDC_GRIDX_EDIT                  1060
#define IDC_GRIDY_EDIT                  1061
#define IDC_RESET                       1062
#define IDC_SETCURVE_BTN                1063
#define IDC_SETGAIN_BTN                 1064
#define IDC_SETGRID_BTN                 1065
#define IDC_VIDEO_RADIO                 1066
#define IDC_WHITE_RADIO                 1067
#define IDC_BLACK_RADIO                 1068
#define IDC_GRAY_RADIO                  1069
#define IDC_GREEN_RADIO                 1070
#define IDC_RED_RADIO                   1071
#define IDC_BLUE_RADIO                  1072
#define IDC_RTSP_URL                    1073
#define IDC_LEN_MINS                    1074
#define IDC_LEN_SECS                    1075
#define IDC_GAMMA_COMBO                 1076
#define IDC_RADIO1                      1077
#define IDC_RADIO2                      1078
#define IDC_RADIO3                      1079
#define IDC_RADIO4                      1080
#define IDC_RADIO5                      1081
#define IDC_RADIO6                      1082
#define IDC_RADIO7                      1083
#define IDC_DATETIMEPICKER1             1084
#define IDC_SAVE_DEFAULT_CHK            1085
#define IDC_INDEX_COMBO                 1086
#define IDC_LOADDEF_STATIC              1087
#define IDC_PANNEL_COMBO                1088
#define IDC_AREA_COMBO                  1089
#define IDC_EBS_COMBO                   1090
#define IDC_EBS_SET_BTN                 1091
#define IDC_EBS_W_EDIT                  1092
#define IDC_EBS_H_EDIT                  1093
#define IDC_EBS_W_STATIC                1094
#define IDC_EBS_H_STATIC                1095
#define IDC_NEXT_BTN                    1096
#define IDC_LEFT_CHK                    1097
#define IDC_TOP_CHK                     1098
#define IDC_RIGHT_CHK                   1099
#define IDC_DOWN_CHK                    1100
#define IDC_EBS_STATIC                  1101
#define IDC_IDX_COMB                    1102
#define IDC_BLEND_GROUP                 1103
#define IDC_LOCK_BLEND_CHK              1104
#define IDC_PRE_BTN                     1105
#define IDC_SOURCE1                     1106
#define IDC_SOURCE2                     1107
#define IDC_SOURCE3                     1108
#define IDC_SOURCE4                     1109
#define IDC_SOURCE5                     1110
#define IDC_SOURCE6                     1111
#define IDC_SOURCE7                     1112
#define IDC_SOURCE8                     1113
#define IDC_SOURCE9                     1114
#define IDC_SOURCE10                    1115
#define IDC_RECREATE                    1116
#define IDC_ENABLE_MAPPING_PF           1117
#define IDC_MAPPING_PROJECT_FILE        1118
#define IDC_BROWSE                      1119
#define IDC_ENABLE_TIMELINE_PF          1120
#define IDC_TIMELINE_PROJECT_FILE       1121
#define IDC_BROWSE2                     1122
#define IDC_STATIC_MSG                  1123
#define IDC_PANEL1_MASK_FILE            1123
#define IDC_GOGAL_TIME_CODE             1124
#define IDC_LOCAL_TIME_CODE             1125
#define IDC_ENABLE_MASK                 1126
#define IDC_BROWSE3                     1127
#define IDC_PANEL2_MASK_FILE            1128
#define IDC_BROWSE4                     1129
#define IDC_PANEL3_MASK_FILE            1130
#define IDC_BROWSE5                     1131
#define IDC_PANEL4_MASK_FILE            1132
#define IDC_BROWSE6                     1133
#define IDC_P1_MAKS_X                   1134
#define IDC_P1_MAKS_Y                   1135
#define IDC_P2_MAKS_X                   1136
#define IDC_P2_MAKS_Y                   1137
#define IDC_P3_MAKS_X                   1138
#define IDC_P3_MAKS_Y                   1139
#define IDC_P4_MAKS_X                   1140
#define IDC_EDIT9                       1141
#define IDC_P4_MAKS_Y                   1141
#define IDC_COMBO1                      1142
#define IDC_MARK_MODE                   1142
#define IDC_TL_FPS                      1142
#define IDC_COMBO2                      1143
#define IDC_TIME_CODE_INTERVAL          1143
#define IDC_TL_FPS2                     1143
#define IDC_MP_FPS                      1143
#define IDC_COMBO3                      1144
#define IDC_DISPLAY_ORDER               1144
#define IDC_STATIC_DISPLAY_FPS          1145
#define IDC_CHECK1                      1146
#define IDC_SYNC                        1146
#define IDC_LANGUAGE                    1147
#define IDC_RUN_NETWORK                 1148
#define IDC_CHECK3                      1149

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1150
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
