#ifndef StringTableInfo_H
#define StringTableInfo_H

typedef struct
{
    unsigned long ulID;
    char szKey[150];
    char* szValue;	
}STableItem;

/*
字串的ID編碼規則:(包含錯誤字串及訊息字串)
ObjID * 65535 + SN
註:ObjID物件或是模組ID，SN為流水號

例如:假設audio的模組ID為1001的話，它的字串ID的範圍為
   (1001 << 16) + 0 ~ (1001 << 16) + 65534

*/

enum TableID
{
    TID_UNKNOWN = 1,
    TID_NORMAL = 10,	
    TID_LOADER,
    TID_DISPLAY,
    TID_DEVICE,
    TID_NET,
    TID_FILE_SYSTEM,
    TID_NOISE_FILTER,
    TID_ALARM,
    TID_SCHEDULE,
    TID_SETTING_DLG,
    TID_EVENT_VIEW,
    TID_HOTLINE, 
	TID_PLAYBACK,
	TID_EMAP,
};

enum LoaderStringTable
{
     ML_CAN_NOT_LOAD_DEVICE = (TID_LOADER << 16),	
     ML_CAN_NOT_LOAD_DISPLAY,
     ML_CAN_NOT_LOAD_NETWORK,
     ML_CAN_NOT_LOAD_FILE_SYSTEM,
     ML_CAN_NOT_LOAD_PLAYBACK,
     ML_CAN_NOT_LOAD_ALARM,
     ML_CAN_NOT_LOAD_SCHEDULE,
     ML_CAN_NOT_LOAD_ACCOUNT,
     ML_CAN_NOT_LOAD_SETTING_DLG,
     ML_CAN_NOT_LOAD_AUDIO,
};

enum SettingDlgStringTable
{
     ML_UI_OK = (TID_SETTING_DLG << 16),	 
     ML_UI_CENCEL,
     
     //skin buttons
     //live
     ML_UI_RECORD,                             //錄影
     ML_UI_NETWORK,                            //網路
     ML_UI_EXIT,
     ML_UI_1CH,
     ML_UI_4CH,
     ML_UI_9CH,
     ML_UI_16CH,
     ML_UI_FOCUS8CH,
     ML_UI_FOCUS13CH,
     ML_UI_EMAP,
     ML_UI_SNAPSHOT,
     ML_UI_SETUP,
     ML_UI_FULLSCREEN,
     ML_UI_EVENT_LOG,
     ML_UI_PLAYLIST,
     
     //playback
     ML_UI_BEGIN,
     ML_UI_PREVIOUS,
     ML_UI_SLOWER,
     ML_UI_REWIND,
     ML_UI_PAUSE,
     ML_UI_PLAY,
     ML_UI_FASTER,
     ML_UI_NEXT,
     ML_UI_END,
     ML_UI_SET_SEGMENT,
     ML_UI_OPUTOU_VIDEO_CLIP,
     ML_UI_BOOKMARK,
     ML_UI_PRINT,
     ML_UI_STOP,
     
     //setting
     ML_UI_CAMERA,                             //攝影機
     ML_UI_SCHEDULE,                           //排程
     ML_UI_ALARM,                              //警報器
     ML_UI_USER_ACCOUNT,                       //使用者帳號
     ML_UI_WAVE,                               //聲音
     ML_UI_GENERAL,                               
     ML_UI_SYSTEM,                             //系統
     ML_UI_ADD,
     ML_UI_DELETE,
     ML_UI_EDIT,
     ML_UI_STORAGE_PATH,
     ML_UI_FOLDER_NAME,
     ML_UI_FREE_SPACE,
     ML_UI_DISK_FREE_USED,
     ML_UI_LANGUAGE,//
     ML_UI_IMPORT,
     ML_UI_EXPORT,
     ML_UI_DATE_FORMAT,
     ML_UI_AUTOSCAN_PERIOD,
     ML_UI_SEC,
     ML_UI_ENABLE,
     ML_UI_VENDOR,
     ML_UI_BACKUP,
     ML_UI_USERNAME,
     ML_UI_PASSWORD,
     ML_UI_NAME,
     ML_UI_SENSOR,
     ML_UI_CONDITIONS,
     ML_UI_TRIGGER_IF_ANY,
     ML_UI_TRIGGER_IF_ALL,
     ML_UI_VIDEO_LOSS,
     ML_UI_REBOOT,
     ML_UI_CONTENT,//
     ML_UI_TEST,
     ML_UI_ABOUT,
     ML_UI_BACK,
     ML_UI_MANUAL_BACKUP,
     ML_UI_AUTO_BACKUP,
     ML_UI_DRIVE_REPEAT,  //This drive was already chosen, please use another disk drive !!!
     ML_UI_CYCLE_TYPE,
     ML_UI_JOB,
     ML_UI_START_TIME,
     ML_UI_END_TIME,
     ML_UI_RECORD_OPTION,
     ML_UI_REBOOT_OPTION,
     ML_UI_START_DATE,//
     ML_UI_SUNDAY,
     ML_UI_MONDAY,
     ML_UI_TUESDAY,
     ML_UI_WENDESDAY,
     ML_UI_THURSDAY,
     ML_UI_FIRDAY,
     ML_UI_SATURDAY,
     ML_UI_DESCRIPTION,
     ML_UI_STATUS,
     ML_UI_BRIGHT,
     ML_UI_CONTRAST,
     ML_UI_HUE,
     ML_UI_SATURATION,
     ML_UI_DEFAULT,
     ML_UI_MOTION_DETECTION,
     ML_UI_AUTOSCAN,
     ML_UI_LIVE_VIEW,
     ML_UI_PLAYBACK,
	 ML_UI_SEARCH,
	 ML_UI_SETTING,
	 ML_UI_CAMERA_NAME,
	 ML_UI_URL,
	 ML_UI_LOGIN,
	 ML_UI_RESOLUTION,
	 ML_UI_SCAN,
	 ML_UI_OPTION,
	 ML_UI_WIZARD_BACK,
	 ML_UI_WIZARD_NEXT,
	 ML_UI_MODE,
	 ML_UI_CHANNEL,
	 ML_UI_SEL_JOB,
	 ML_UI_SEL_DAYS,
	 ML_UI_HOTLINE,
	 ML_UI_ACTIONS,
	 ML_UI_OTHER,
	 ML_UI_LANGUAGE_EN,
	 ML_UI_LANGUAGE_TC,
	 ML_UI_LANGUAGE_SC,
	 ML_UI_OUTPUTVIDEO_MSG1,
	 ML_UI_OUTPUTVIDEO_MSG2,
	 ML_UI_IP_CAM_SEARCH,
	 ML_UI_VERSION,
	 ML_UI_MODEL,
	 ML_UI_GROUP,
	 ML_UI_ADMINISTRATOR,
	 ML_UI_USER,
	 ML_UI_SIZE,
     ML_UI_INTELLIGENT_SEARCH,
};

enum EventViewStringTable
{
	ML_EVENT_ALARM = (TID_EVENT_VIEW << 16),
        ML_EVENT_OPERATION,
        ML_EVENT_NETWORK,
        ML_EVENT_SYSTEM,
        ML_EVENT_EVENT,
        ML_EVENT_NO,
        ML_EVENT_DATE_TIME,
        ML_EVENT_CAMERA,
        ML_EVENT_TYPE,
        ML_EVENT_DESCRIPTION,
        ML_EVENT_DATE,
        ML_EVENT_TO,
        ML_EVENT_EVENT_TYPE,
};

enum AlarmStringTable
{
	ML_ALARM_OK = (TID_ALARM << 16),
        ML_ALARM_BACK,
        ML_ALARM_NEXT,
        ML_ALARM_ENABLE,
        ML_ALARM_EVENT_TYPE,
        ML_ALARM_MOTOIN,
        ML_ALARM_SIGNAL_LOST,
        ML_ALARM_OPTION,
        ML_ALARM_CHANNEL,
        ML_ALARM_NAME,
        ML_ALARM_DESCRIPTION,
        ML_ALARM_ACCIVATED_PERIOD,
        ML_ALARM_ALWAYS,
        ML_ALARM_PERIOD,
        ML_ALARM_LIFE_CYCLE,
        ML_ALARM_AUTOMATIC,
        ML_ALARM_MANUAL,
        ML_ALARM_TIMEOUT,
        ML_ALARM_SEC,
        ML_ALARM_ACTION_TYPE,
        ML_ALARM_PLAY_SOUND,
        ML_ALARM_SEND_EMAIL,
        ML_ALARM_FTP,
        ML_ALARM_BOOKMARK,
		ML_ALARM_CLEAN_ALL,
		ML_ALARM_ALARM_REPORT,
		ML_ALARM_OBJECT_DETECTION,
		ML_ALARM_ADVANCED,
		ML_ALARM_SIMULATION,
		ML_ALARM_SENSITIVITY,
		ML_ALARM_INVERT,
		ML_ALARM_CLEAN,
		ML_ALARM_ALARM_EVENT_CONFIG,
};

enum HotlineStringTable
{
	ML_HL_EMAIL = (TID_HOTLINE << 16),
        ML_HL_MAIL_SERVER,
        ML_HL_SMTP_SERVER,
        ML_HL_AUTHENTICATION,
        ML_HL_EMAIL_ID,
        ML_HL_EMAIL_PW,
        ML_HL_MAIL,
        ML_HL_HTML,
        ML_HL_FROM,
        ML_HL_TO,
        ML_HL_CC,
        ML_HL_SUBJECT,
        ML_HL_MESSAGE_TEXT,
        ML_HL_FTP,
        ML_HL_FTP_SERVER,
        ML_HL_FTP_PORT,
        ML_HL_FTP_ID,
        ML_HL_FTP_PW,
};

enum PlaybackStringTable
{
	ML_PB_OK = (TID_PLAYBACK << 16),
    ML_PB_CANCEL,
	ML_PB_PLAYLIST,
	ML_PB_EDIT_BOOKMARK,
	ML_PB_TIME,
	ML_PB_MARK,
	ML_PB_BOOKMARK,
	ML_PB_ADD,
	ML_PB_EDIT,
	ML_PB_DELETE,
	ML_PB_NO,
	ML_PB_STATUS,
	ML_PB_SECTION,
	ML_PB_DURATION,
	ML_PB_CHANNELS,
};

enum EMapStringTable
{
	ML_EM_EMAP = (TID_EMAP << 16),
	ML_EM_SAVE,
	ML_EM_ADD,
	ML_EM_EDIT,
	ML_EM_DELETE,
	ML_EM_OK,
	ML_EM_CANCEL,
	ML_EM_IMAGE_FILE,
	ML_EM_MAP_CONFIG,
	ML_EM_NAME,
	ML_EM_NO,
	ML_EM_OPERATE_MODE,
	ML_EM_EDIT_MODE,
};

//給編輯器使用的資訊
//Language Identifiers
#ifdef _EDIT_STRING_ID

typedef struct
{
    char szName[150];
    unsigned long ulID;
    int iMaxLen;	        //-1表示長度不限
}EditItem;

//static int g_iTotalOfEditItems = 197;
static EditItem g_EditItems[] = 
{
   //for loader error message    (11)	
   {"Can not load device plugin",ML_CAN_NOT_LOAD_DEVICE,-1},	
   {"Can not load display plugin",ML_CAN_NOT_LOAD_DISPLAY,-1},
   {"Can not load network plugin",ML_CAN_NOT_LOAD_NETWORK,-1},
   {"Can not load file system plugin",ML_CAN_NOT_LOAD_FILE_SYSTEM,-1},
   {"Can not load playback plugin",ML_CAN_NOT_LOAD_PLAYBACK,-1},
   {"Can not load alarm plugin",ML_CAN_NOT_LOAD_ALARM,-1},
   {"Can not load schedule plugin",ML_CAN_NOT_LOAD_SCHEDULE,-1},
   {"Can not load account manager plugin",ML_CAN_NOT_LOAD_ACCOUNT,-1},
   {"Can not load config plugin",ML_CAN_NOT_LOAD_SETTING_DLG,-1},
   {"Can not load audio plugin",ML_CAN_NOT_LOAD_AUDIO,-1},
   
   //UI
   {"OK",ML_UI_OK,-1},
   {"Cancel",ML_UI_CENCEL,-1},
   {"Record",ML_UI_RECORD,-1},
   {"Network",ML_UI_NETWORK,-1},
   {"Exit",ML_UI_EXIT,-1},
   {"1 Channel",ML_UI_1CH,-1},
   {"4 Channels",ML_UI_4CH,-1},
   {"9 Channels",ML_UI_9CH,-1},
   {"16 Channels",ML_UI_16CH,-1},
   {"Focus 8 Channels",ML_UI_FOCUS8CH,-1},
   {"Focus 13 Channels",ML_UI_FOCUS13CH,-1},
   {"E-Map",ML_UI_EMAP,-1},
   {"Snapshot",ML_UI_SNAPSHOT,-1},
   {"Setup",ML_UI_SETUP,-1},
   {"Full Screen",ML_UI_FULLSCREEN,-1},
   {"Event Log",ML_UI_EVENT_LOG,-1},
   {"Playlist",ML_UI_PLAYLIST,-1},
   
   {"Begin",ML_UI_BEGIN,-1},
   {"Previous",ML_UI_PREVIOUS,-1},
   {"Slower",ML_UI_SLOWER,-1},
   {"Rewind",ML_UI_REWIND,-1},
   {"Pause",ML_UI_PAUSE,-1},
   {"Play",ML_UI_PLAY,-1},
   {"Faster",ML_UI_FASTER,-1},
   {"Next",ML_UI_NEXT,-1},
   {"End",ML_UI_END,-1},
   {"Set Segment",ML_UI_SET_SEGMENT,-1},
   {"Output Video Clip",ML_UI_OPUTOU_VIDEO_CLIP,-1},
   {"Bookmark",ML_UI_BOOKMARK,-1},
   {"Print",ML_UI_PRINT,-1},
   {"Stop",ML_UI_STOP,-1},
   
   {"Camera",ML_UI_CAMERA,-1},
   {"Schedule",ML_UI_SCHEDULE,-1},
   {"Alarm",ML_UI_ALARM,-1},
   {"User Account",ML_UI_USER_ACCOUNT,-1},
   {"Wave",ML_UI_WAVE,-1},
   {"General",ML_UI_GENERAL,-1},
   {"System",ML_UI_SYSTEM,-1},
   {"Add",ML_UI_ADD,-1},
   {"Delete",ML_UI_DELETE,-1},
   {"Edit",ML_UI_EDIT,-1},
   {"Storage Path",ML_UI_STORAGE_PATH,-1},
   {"Folder Name",ML_UI_FOLDER_NAME,-1},
   {"Free Space",ML_UI_FREE_SPACE,-1},
   {"Disk Space(Used)",ML_UI_DISK_FREE_USED,-1},
   {"Language",ML_UI_LANGUAGE,-1},
   {"Import",ML_UI_IMPORT,-1},
   {"Export",ML_UI_EXPORT,-1},
   {"Date Format",ML_UI_DATE_FORMAT,-1},
   {"Autoscan Period",ML_UI_AUTOSCAN_PERIOD,-1},
   {"Sec.",ML_UI_SEC,-1},
   {"Enable",ML_UI_ENABLE,-1},
   {"Vendor",ML_UI_VENDOR,-1},
   {"Backup",ML_UI_BACKUP,-1},
   {"UserName",ML_UI_USERNAME,-1},
   {"Password",ML_UI_PASSWORD,-1},
   {"Name",ML_UI_NAME,-1},
   {"Sensor",ML_UI_SENSOR,-1},
   {"Conditions",ML_UI_CONDITIONS,-1},
   {"Trigger If Any",ML_UI_TRIGGER_IF_ANY,-1},
   {"Trigger If All",ML_UI_TRIGGER_IF_ALL,-1},
   {"Video Loss",ML_UI_VIDEO_LOSS,-1},
   {"Reboot",ML_UI_REBOOT,-1},
   {"Content",ML_UI_CONTENT,-1},
   
   {"Test",ML_UI_TEST,-1},
   {"About",ML_UI_ABOUT,-1},
   {"Back",ML_UI_BACK,-1},
   {"Manual Backup",ML_UI_MANUAL_BACKUP,-1},
   {"Auto Backup",ML_UI_AUTO_BACKUP,-1},
   {"This drive was already chosen,please use another disk drive!",ML_UI_DRIVE_REPEAT,-1},
   {"Cycle Type",ML_UI_CYCLE_TYPE,-1},
   {"Job",ML_UI_JOB,-1},
   {"Start Time",ML_UI_START_TIME,-1},
   {"End Time",ML_UI_END_TIME,-1},
   {"Record Option",ML_UI_RECORD_OPTION,-1},
   {"Reboot Option",ML_UI_REBOOT_OPTION,-1},
   {"Start Date",ML_UI_START_DATE,-1},
   
   {"Sunday",ML_UI_SUNDAY,-1},
   {"Monday",ML_UI_MONDAY,-1},
   {"Tuesday",ML_UI_TUESDAY,-1},
   {"Wendsday",ML_UI_WENDESDAY,-1},
   {"Thursday",ML_UI_THURSDAY,-1},
   {"Firday",ML_UI_FIRDAY,-1},
   {"Saturday",ML_UI_SATURDAY,-1},
   {"Description",ML_UI_DESCRIPTION,-1},
   {"Status",ML_UI_STATUS,-1},
   {"Bright",ML_UI_BRIGHT,-1},
   {"Contrast",ML_UI_CONTRAST,-1},
   {"Hue",ML_UI_HUE,-1},
   {"Saturation",ML_UI_SATURATION,-1},
   {"Default",ML_UI_DEFAULT,-1},
   {"Motion Detection",ML_UI_MOTION_DETECTION,-1},
   {"AutoScan",ML_UI_AUTOSCAN,-1},
   {"Live View",ML_UI_LIVE_VIEW,-1},
   {"Playback",ML_UI_PLAYBACK,-1},
   {"Search",ML_UI_SEARCH,-1},
   {"Setting",ML_UI_SETTING,-1},
   {"Camera Name",ML_UI_CAMERA_NAME,-1},
   {"Url",ML_UI_URL,-1},
   {"Login",ML_UI_LOGIN,-1},
   {"Resolution",ML_UI_RESOLUTION,-1},
   {"Scan",ML_UI_SCAN,-1},
   {"Option",ML_UI_OPTION,-1},
   {"< Back",ML_UI_WIZARD_BACK,-1},
   {"Next >",ML_UI_WIZARD_NEXT,-1},
   {"Mode",ML_UI_MODE,-1},
   {"Channel",ML_UI_CHANNEL,-1},
   {"Select Job",ML_UI_SEL_JOB,-1},
   {"Select Days",ML_UI_SEL_DAYS,-1},

   {"Alarm",ML_EVENT_ALARM,-1},
   {"Operation",ML_EVENT_OPERATION,-1},
   {"Network",ML_EVENT_NETWORK,-1},
   {"System",ML_EVENT_SYSTEM,-1},
   {"Event",ML_EVENT_EVENT,-1},
   {"No.",ML_EVENT_NO,-1},
   {"Date/Time",ML_EVENT_DATE_TIME,-1},
   {"Camera",ML_EVENT_CAMERA,-1},
   {"Type",ML_EVENT_TYPE,-1},
   {"Description",ML_EVENT_DESCRIPTION,-1},
   {"Date",ML_EVENT_DATE,-1},
   {"To",ML_EVENT_TO,-1},
   {"Event Type",ML_EVENT_EVENT_TYPE,-1},

   {"OK",ML_ALARM_OK,-1},
   {"Back",ML_ALARM_BACK,-1},
   {"Next",ML_ALARM_NEXT,-1},
   {"Enable",ML_ALARM_ENABLE,-1},
   {"Event Type",ML_ALARM_EVENT_TYPE,-1},
   {"Motion",ML_ALARM_MOTOIN,-1},
   {"Signal Lost",ML_ALARM_SIGNAL_LOST,-1},
   {"Option",ML_ALARM_OPTION,-1},
   {"Channel",ML_ALARM_CHANNEL,-1},
   {"Name",ML_ALARM_NAME,-1},
   {"Description",ML_ALARM_DESCRIPTION,-1},
   {"Activated Period",ML_ALARM_ACCIVATED_PERIOD,-1},
   {"Always activated",ML_ALARM_ALWAYS,-1},
   {"Activated only in the following period",ML_ALARM_PERIOD,-1},
   {"Life Cycle",ML_ALARM_LIFE_CYCLE,-1},
   {"Automatic cancel event when event disappear",ML_ALARM_AUTOMATIC,-1},
   {"Manual cancel event or event last triggered",ML_ALARM_MANUAL,-1},
   {"Cancel event after",ML_ALARM_TIMEOUT,-1},
   {"Sec",ML_ALARM_SEC,-1},
   {"Action Type",ML_ALARM_ACTION_TYPE,-1},
   {"Play Sound",ML_ALARM_PLAY_SOUND,-1},
   {"Send E-Mail",ML_ALARM_SEND_EMAIL,-1},
   {"FTP",ML_ALARM_FTP,-1},
   {"BookMark",ML_ALARM_BOOKMARK,-1},

   {"E-Mail",ML_HL_EMAIL,-1},
   {"Mail Server",ML_HL_MAIL_SERVER,-1},
   {"SMTP Server",ML_HL_SMTP_SERVER,-1},
   {"Authentication",ML_HL_AUTHENTICATION,-1},
   {"ID:",ML_HL_EMAIL_ID,-1},
   {"Password:",ML_HL_EMAIL_PW,-1},
   {"Mail",ML_HL_MAIL,-1},
   {"HTML format support",ML_HL_HTML,-1},
   {"From:",ML_HL_FROM,-1},
   {"To:",ML_HL_TO,-1},
   {"CC:",ML_HL_CC,-1},
   {"Subject:",ML_HL_SUBJECT,-1},
   {"Message text",ML_HL_MESSAGE_TEXT,-1},
   {"FTP",ML_HL_FTP,-1},
   {"FTP Server",ML_HL_FTP_SERVER,-1},
   {"Port",ML_HL_FTP_PORT,-1},
   {"Account:",ML_HL_FTP_ID,-1},
   {"Password:",ML_HL_FTP_PW,-1},

   {"Hotline",ML_UI_HOTLINE,-1},
   {"Actions",ML_UI_ACTIONS,-1},

   {"OK",ML_PB_OK,-1},
   {"Cancel",ML_PB_CANCEL,-1},
   {"Playlist",ML_PB_PLAYLIST,-1},
   {"Edit Bookmark",ML_PB_EDIT_BOOKMARK,-1},
   {"Time",ML_PB_TIME,-1},
   {"Mark",ML_PB_MARK,-1},
   {"Bookmark",ML_PB_BOOKMARK,-1},
   {"Add",ML_PB_ADD,-1},
   {"Edit",ML_PB_EDIT,-1},
   {"Delete",ML_PB_DELETE,-1},
   {"No.",ML_PB_NO,-1},
   {"Status",ML_PB_STATUS,-1},
   {"Section",ML_PB_SECTION,-1},
   {"Duration",ML_PB_DURATION,-1},
   {"Channels",ML_PB_CHANNELS,-1},

   {"E-Map",ML_EM_EMAP,-1},
   {"Save",ML_EM_SAVE,-1},
   {"Add",ML_EM_ADD,-1},
   {"Edit",ML_EM_EDIT,-1},
   {"Delete",ML_EM_DELETE,-1},
   {"OK",ML_EM_OK,-1},
   {"Cancel",ML_EM_CANCEL,-1},
   {"Image File",ML_EM_IMAGE_FILE,-1},
   {"Map Config",ML_EM_MAP_CONFIG,-1},
   {"Name",ML_EM_NAME,-1},
   {"No.",ML_EM_NO,-1},
   {"Operate Mode",ML_EM_OPERATE_MODE,-1},
   {"Edit Mode",ML_EM_EDIT_MODE,-1},
   {"Clean All",ML_ALARM_CLEAN_ALL,-1},
   {"Alarm Report",ML_ALARM_ALARM_REPORT,-1},

   {"Other",ML_UI_OTHER,-1},
   {"English",ML_UI_LANGUAGE_EN,-1},
   {"Chinese(Traditional)",ML_UI_LANGUAGE_TC,-1},
   {"Chinese(Simplified)",ML_UI_LANGUAGE_SC,-1},

   {"Please use <Segment> to mark your target video segment first!",ML_UI_OUTPUTVIDEO_MSG1,-1},
   {"Video segment duration must be longer than 1 second!",ML_UI_OUTPUTVIDEO_MSG2,-1},

   {"Object Detection",ML_ALARM_OBJECT_DETECTION,-1},
   {"Advanced",ML_ALARM_ADVANCED,-1},
   {"Simulation",ML_ALARM_SIMULATION,-1},
   {"Sensitivity",ML_ALARM_SENSITIVITY,-1},
   {"Invert",ML_ALARM_INVERT,-1},
   {"Clean",ML_ALARM_CLEAN,-1},
   {"Alarm Event Configuration",ML_ALARM_ALARM_EVENT_CONFIG,-1},

   {"IP Cam Search",ML_UI_IP_CAM_SEARCH,-1},
   {"Version",ML_UI_VERSION,-1},
   {"Model",ML_UI_MODEL,-1},

   {"Gropu",ML_UI_GROUP,-1},
   {"Administrator",ML_UI_ADMINISTRATOR,-1},
   {"User",ML_UI_USER,-1},
   {"Size",ML_UI_SIZE,-1},
   {"Intelligent Search",ML_UI_INTELLIGENT_SEARCH,-1},
};

static int g_iTotalOfEditItems = sizeof(g_EditItems)/sizeof(EditItem);
#endif
#endif